version: 0.0
os: linux

files:
   - source: target/controller-1.0.0-BUILD-SNAPSHOT.war
     destination: /home/ec2-user/tomcat/webapps/app.war
#    - source: /index.html
#      destination: /var/www/html

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root 
