version: 0.2

phases:
 install:
   runtime-versions:
     java: corretto17
 pre_build:
   commands:
#    - mvn install:install-file -Dfile=ojdbc8.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.2.0.1 -Dpackaging=jar
 build:
   commands:
     - mvn package
 post_build:
   commands:
     ## aws s3 cp target/*.war s3://myhhbucket23 . We don't need this step.
#     - aws s3 cp target/*.war s3://codepipeline-ap-northeast-2-177605922035/app.war
     - echo Build completed
artifacts:
  files:
    - target/controller-1.0.0-BUILD-SNAPSHOT.war
#     - index.html
#    - scripts/server_start.sh
#    - scripts/server_stop.sh
    - appspec.yml
    - dist/**/*
#  base-directory: build
   
#  discard-paths: yes
